theme: jekyll-theme-merlot

title: "Tonnelon"
description: "Willkommen bei Tonnelon.de"

# Optionaler Infotext für die Startseite (kann in index.md genutzt werden)
intro_text: >
  Leider musste ich meinen Webshop nach fast 30 Jahren schließen. 
  Anscheinend spielen Väter heute lieber mit ihren Kindern an der Playstation, 
  anstatt gemeinsam Modelle zusammenzubauen :-(
  Sie können noch einige Restbestände meiner Modelle über EBAY erhalten – 
  suchen Sie einfach bei EBAY nach Tonnelon.

show_downloads: false
